### ISSUE TITLE
Future Client - `getTradingPairFee` param typo

### ISSUE THREAD

**Issue by abellsmythe** [tiagosiebler/kucoin-api#29]
Hello!! 👋🏼 

There is a typo in the params of the `FuturesClient.getTradingPairFee`, which currently expects `symbols`, I think the method should look like this

```ts
getTradingPairFee(params: { symbol: string }): Promise<
    APISuccessResponse<{
      symbol: string;
      takerFeeRate: string;
      makerFeeRate: string;
    }>
  > {
    return this.getPrivate('api/v1/trade-fees', params);
  }
```

When sending `symbols` I got a 400 Bad Request response from the Kucoin API

As reference [Trading pair actual fee - Futures](https://www.kucoin.com/docs/rest/funding/trade-fee/trading-pair-actual-fee-futures)

**Comment by abellsmythe** [comment]
@tiagosiebler let me know if I can help with this one

Btw, thanks for the great SDK! 💪🏼

**Comment by JJ-Cro** [comment]
Thanks, let me check!

**Comment by JJ-Cro** [comment]
PR is active: https://github.com/tiagosiebler/kucoin-api/pull/30

Lets wait for Tiago to merge. @abellsmythe  thanks for letting us know, typos happen ! If you see anything else, let us know and we will take care of it asap :)

**Comment by tiagosiebler** [comment]
Merged! Thanks @JJ-Cro for the quick PR, and thanks @abellsmythe for reporting it & offering to PR it. PRs always welcome but also appreciate reports like this in case you can't PR at the time.
